- name: configure DB server
  hosts: db
  become: yes
  vars:
   login_host: db.rskothapalli.site # we don 't creae this variable until we reach script to login-host.
  vars_prompt:
  - name: mysql_root_password
    prompt: pleaes enter MYSQL root password
    private: no

  tasks:
    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest
    - name: start and enable mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: install mysql python dependencies
      ansible.builtin.pip:
        name: 
        - PyMySQL
        - cryptography
        exedutable: pip3.9
     # check if password is already set up or not. 
    - name: check db connection
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: "{{login_host}}"
        filter: version #it is used to check the version. 
      ignore_errors: yes
      register: mysql_connection_output
    - name: print output
      ansible.builtin.debug:
        msg: "Output: {{mysql_connection_output}}"
    - name: set up root password
      ansible.builtin.command: "mysql_secure_installation --set root pass {{ mysql}_root_password }"
      when: sql_connection_output.failed is true #don't give {{ }} in when condition. also it's not True but it's true. 
